import Foundation

/// The 30-level campaign: ten architectures, three puzzles each.
public enum LevelPack {
    public static let levels: [Level] = build()

    public static func levels(in chapter: Chapter) -> [Level] {
        levels.filter { $0.chapter == chapter }
    }

    public static func level(id: String) -> Level? {
        levels.first { $0.id == id }
    }

    /// The level after `level` in campaign order, if any.
    public static func next(after level: Level) -> Level? {
        guard let i = levels.firstIndex(of: level), i + 1 < levels.count else { return nil }
        return levels[i + 1]
    }

    private static func build() -> [Level] {
        do {
            return try specs.map { try $0.level() }
        } catch {
            preconditionFailure("Invalid built-in level: \(error)")
        }
    }

    struct Spec {
        var chapter: Chapter
        var index: Int
        var title: String
        var board: String
        var solution: String
        var colors: [GridPoint: BeamColor] = [:]
        var hint: String? = nil

        var id: String { "\(chapter.name.lowercased())-\(index)" }

        func level() throws -> Level {
            try LevelSpec.parse(id: id, title: title, chapter: chapter, index: index,
                                board: board, solution: solution, colors: colors, hint: hint)
        }
    }

    // swiftlint:disable line_length
    static let specs: [Spec] = [
        // MARK: Fermi — mirrors
        Spec(chapter: .fermi, index: 1, title: "First Light",
             board: """
             .....
             .....
             >....
             .....
             .....
             .....
             ...O.
             """,
             solution: """
             .....
             .....
             ...\\.
             .....
             .....
             .....
             .....
             """,
             hint: "Tap a cell to place a mirror. Tap it again to flip it."),
        Spec(chapter: .fermi, index: 2, title: "Two Bounces",
             board: """
             v....
             .....
             .....
             .....
             .....
             #....
             #...O
             """,
             solution: """
             .....
             .....
             .....
             .....
             \\...\\
             .....
             .....
             """,
             hint: "Turn before the wall, then turn again."),
        Spec(chapter: .fermi, index: 3, title: "Around the Box",
             board: """
             .v.....
             .......
             .......
             ...#.#.
             ...#O#.
             ...###.
             .......
             .......
             .......
             """,
             solution: """
             .......
             .\\..\\..
             .......
             .......
             .......
             .......
             .......
             .......
             .......
             """,
             hint: "The box is open at the top."),

        // MARK: Kepler — walls
        Spec(chapter: .kepler, index: 1, title: "Switchback",
             board: """
             >......
             .......
             .#.....
             .......
             .......
             .......
             .......
             .......
             .O.#...
             """,
             solution: """
             .....\\.
             .......
             .......
             .......
             ./.../.
             .......
             .......
             .......
             .......
             """,
             hint: "Down, across, down."),
        Spec(chapter: .kepler, index: 2, title: "Corridor",
             board: """
             ......O
             .......
             .###...
             .......
             ...#...
             .......
             .###...
             .......
             ...^...
             """,
             solution: """
             .......
             .......
             .......
             .......
             .......
             .......
             .......
             .../../
             .......
             """,
             hint: "Only two corridors lead to the far column."),
        Spec(chapter: .kepler, index: 3, title: "Pinball",
             board: """
             .......
             .......
             .......
             .......
             >..#...
             .......
             .......
             ....#.O
             .......
             """,
             solution: """
             .......
             ./....\\
             .......
             .......
             ./.....
             .......
             .......
             .......
             .......
             """,
             hint: "Go up and over."),

        // MARK: Maxwell — fixed optics
        Spec(chapter: .maxwell, index: 1, title: "Inherited Optics",
             board: """
             .......
             .......
             >....\\.
             .......
             .......
             .......
             .O.....
             .......
             .......
             """,
             solution: """
             .......
             .......
             .......
             .......
             .......
             .......
             ...../.
             .......
             .......
             """,
             hint: "The grey mirror is bolted down. Work with it."),
        Spec(chapter: .maxwell, index: 2, title: "Bank Shot",
             board: """
             ...v...
             .......
             .......
             \\../...
             .......
             .......
             .......
             .......
             ......O
             """,
             solution: """
             .......
             /.....\\
             .......
             .......
             .......
             .......
             .......
             .......
             .......
             """,
             hint: "Follow the fixed mirrors up, then cross the top."),
        Spec(chapter: .maxwell, index: 3, title: "Hall of Mirrors",
             board: """
             >...\\..
             .......
             .......
             ..\\./..
             .......
             .......
             ....../
             .......
             O......
             """,
             solution: """
             .......
             /.\\....
             .......
             .......
             .......
             .......
             .......
             .......
             .......
             """,
             hint: "One of the fixed mirrors is a decoy."),

        // MARK: Pascal — splitters
        Spec(chapter: .pascal, index: 1, title: "Split Decision",
             board: """
             ...O...
             .......
             .......
             .......
             >.....O
             .......
             .......
             .......
             .......
             """,
             solution: """
             .......
             .......
             .......
             .......
             ...S...
             .......
             .......
             .......
             .......
             """,
             hint: "A splitter passes the beam and reflects it."),
        Spec(chapter: .pascal, index: 2, title: "Fan Out",
             board: """
             .......
             >.....O
             .......
             .......
             .......
             .......
             .....O.
             .......
             ..O....
             """,
             solution: """
             .......
             ..Z....
             .......
             .......
             .......
             .......
             ..Z....
             .......
             .......
             """,
             hint: "Split twice along the same column."),
        Spec(chapter: .pascal, index: 3, title: "Three-Way",
             board: """
             ...v...
             .......
             .......
             O.....O
             .......
             .......
             .......
             .......
             ...O...
             """,
             solution: """
             .......
             .......
             .......
             ...S...
             .......
             ...Z../
             .......
             .......
             .......
             """,
             hint: "The right-hand target needs a bounce back up."),

        // MARK: Volta — multiple sources
        Spec(chapter: .volta, index: 1, title: "Twin Beams",
             board: """
             .....O.
             >......
             .......
             .......
             .......
             .......
             .......
             >......
             ...O...
             """,
             solution: """
             .......
             ...\\...
             .......
             .......
             .......
             .......
             .......
             ...../.
             .......
             """,
             hint: "Beams cross without interfering."),
        Spec(chapter: .volta, index: 2, title: "Crossfire",
             board: """
             .v.....
             .......
             .......
             .......
             ......<
             .......
             ......O
             .......
             ...O...
             """,
             solution: """
             .......
             .......
             .......
             .......
             .../...
             .......
             .\\.....
             .......
             .......
             """,
             hint: "Beams pass straight through each other."),
        Spec(chapter: .volta, index: 3, title: "Three Sources",
             board: """
             >......
             .......
             v......
             .......
             #..O...
             .......
             .O.....
             .......
             ......<
             """,
             solution: """
             ...\\...
             .......
             .......
             \\\\.....
             .......
             .......
             .......
             .......
             ...\\...
             """,
             hint: "Two beams may share one target."),

        // MARK: Turing — colour filters
        Spec(chapter: .turing, index: 1, title: "Filter",
             board: """
             .......
             .......
             .......
             .......
             >.....R
             .......
             .......
             .......
             .......
             """,
             solution: """
             .......
             .......
             .......
             .......
             ...F...
             .......
             .......
             .......
             .......
             """,
             colors: [GridPoint(0, 4): .white, GridPoint(3, 4): .red],
             hint: "White light carries every colour. A filter keeps one."),
        Spec(chapter: .turing, index: 2, title: "Two Channels",
             board: """
             ...B...
             .......
             >.....R
             .......
             .......
             .......
             .......
             .......
             .......
             """,
             solution: """
             .......
             ...F...
             ...S.F.
             .......
             .......
             .......
             .......
             .......
             .......
             """,
             colors: [GridPoint(0, 2): .white, GridPoint(3, 1): .blue, GridPoint(5, 2): .red],
             hint: "Split first, filter each branch."),
        Spec(chapter: .turing, index: 3, title: "Primary Colours",
             board: """
             .......
             >......
             ......B
             .......
             >.....O
             .......
             ......R
             >......
             .......
             """,
             solution: """
             .......
             ..\\....
             ./.....
             .......
             .......
             .......
             ..\\....
             ./.....
             .......
             """,
             colors: [GridPoint(0, 1): .red, GridPoint(0, 7): .blue],
             hint: "A target absorbs any beam, even the wrong colour."),

        // MARK: Ampere — additive mixing
        Spec(chapter: .ampere, index: 1, title: "Additive",
             board: """
             .......
             .......
             >......
             .......
             ......Y
             .......
             .......
             .......
             ......^
             """,
             solution: """
             .......
             .......
             ..\\....
             .......
             ..\\....
             .......
             .......
             .......
             .......
             """,
             colors: [GridPoint(0, 2): .red],
             hint: "Red plus green makes yellow."),
        Spec(chapter: .ampere, index: 2, title: "White Balance",
             board: """
             .......
             >......
             .......
             .......
             >.....W
             .......
             .......
             >......
             .......
             """,
             solution: """
             .......
             ......\\
             .......
             .......
             .......
             .......
             .......
             ....../
             .......
             """,
             colors: [GridPoint(0, 1): .red, GridPoint(0, 7): .blue],
             hint: "All three primaries on one target."),
        Spec(chapter: .ampere, index: 3, title: "Subtractive",
             board: """
             ...Y...
             .......
             .......
             .......
             >......
             .......
             .......
             .......
             ...C...
             """,
             solution: """
             .......
             .......
             ...F...
             .......
             ...S.\\.
             .......
             .......
             .......
             ....F/.
             """,
             colors: [GridPoint(0, 4): .white, GridPoint(3, 2): .yellow, GridPoint(4, 8): .cyan],
             hint: "Yellow and cyan filters each keep two primaries."),

        // MARK: Hopper — split spectra
        Spec(chapter: .hopper, index: 1, title: "Bus",
             board: """
             ...v...
             .......
             ...Z..R
             .......
             .......
             ...Z..B
             .......
             .......
             ...O...
             """,
             solution: """
             .......
             .......
             .....F.
             .......
             .......
             .....F.
             .......
             ...F...
             .......
             """,
             colors: [GridPoint(3, 0): .white, GridPoint(5, 2): .red, GridPoint(5, 5): .blue, GridPoint(3, 7): .green],
             hint: "The splitters are fixed. Colour each branch."),
        Spec(chapter: .hopper, index: 2, title: "Recombine",
             board: """
             .......
             >......
             ......#
             .......
             ......M
             .......
             .......
             >......
             .......
             """,
             solution: """
             .......
             ...\\...
             .......
             .......
             ...\\...
             .......
             .......
             ....../
             .......
             """,
             colors: [GridPoint(0, 1): .red, GridPoint(0, 7): .blue],
             hint: "Red plus blue makes magenta."),
        Spec(chapter: .hopper, index: 3, title: "Spectrum",
             board: """
             .......
             ......R
             .......
             .......
             >.....O
             .......
             .......
             ......B
             .......
             """,
             solution: """
             .......
             ../.F..
             .......
             .......
             ..S.ZF.
             .......
             .......
             ....\\F.
             .......
             """,
             colors: [GridPoint(0, 4): .white, GridPoint(4, 1): .red, GridPoint(5, 4): .green, GridPoint(5, 7): .blue],
             hint: "One white beam, three primaries."),

        // MARK: Blackwell — everything at scale
        Spec(chapter: .blackwell, index: 1, title: "Datacenter",
             board: """
             v.#.#..
             ..#.#.O
             ..#.#..
             .......
             ..#.#..
             ..#.#..
             ..#.#..
             .......
             ......O
             """,
             solution: """
             .......
             ...../.
             .......
             \\..Z./.
             .......
             .......
             .......
             ...\\..\\
             .......
             """,
             hint: "Two aisles cross the racks."),
        Spec(chapter: .blackwell, index: 2, title: "NVLink",
             board: """
             v......
             .......
             .......
             .......
             >..W...
             .......
             .......
             .......
             ......^
             """,
             solution: """
             .......
             .......
             \\..\\...
             .......
             .......
             .......
             ...\\..\\
             .......
             .......
             """,
             colors: [GridPoint(0, 0): .red, GridPoint(6, 8): .blue],
             hint: "Three primaries converge from three sides."),
        Spec(chapter: .blackwell, index: 3, title: "Tensor Core",
             board: """
             ...R...
             .......
             ......O
             .......
             >......
             .......
             .......
             .......
             ...B...
             """,
             solution: """
             .......
             ...F...
             .......
             ......F
             ...S.Z/
             .......
             .......
             .......
             ....F/.
             """,
             colors: [GridPoint(0, 4): .white, GridPoint(3, 1): .red, GridPoint(6, 3): .green, GridPoint(4, 8): .blue],
             hint: "Split, split again, then filter every branch."),

        // MARK: Rubin — interference
        Spec(chapter: .rubin, index: 1, title: "Interference",
             board: """
             .......
             .......
             >.....O
             .......
             .......
             .......
             >.....R
             .......
             .......
             """,
             solution: """
             .......
             .......
             .....\\.
             ./..../
             .......
             .......
             ./...\\.
             .......
             .......
             """,
             colors: [GridPoint(0, 2): .red],
             hint: "Swap lanes without letting the beams meet on a mirror."),
        Spec(chapter: .rubin, index: 2, title: "Full Spectrum",
             board: """
             ...v...
             .......
             R......
             .......
             ......O
             .......
             Y......
             .......
             ...BC..
             """,
             solution: """
             .......
             .......
             .F.S...
             .......
             ...ZZF.
             .......
             .F.SF..
             ...F...
             .......
             """,
             colors: [GridPoint(3, 0): .white, GridPoint(1, 2): .red, GridPoint(4, 6): .cyan, GridPoint(5, 4): .green,
                      GridPoint(1, 6): .yellow, GridPoint(3, 7): .blue],
             hint: "Five targets, one source. Order matters."),
        Spec(chapter: .rubin, index: 3, title: "Ouroboros",
             board: """
             .......
             .......
             ../..\\.
             ......O
             >.....#
             ....#..
             ..\\../.
             .......
             ....O..
             """,
             solution: """
             .......
             .......
             .......
             .....Z.
             ..S....
             .......
             ....S..
             .......
             .......
             """,
             hint: "Feed the loop, then bleed light out of it."),
    ]
    // swiftlint:enable line_length
}
